config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :start_time, presence: true
    validates :end_time, presence: true
    validates :start_time, comparison: { less_than: :end_time }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: %i[ show edit update ]

    def show; end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(event_params)
        
        if @event.save
            redirect_to root_path, notice: 'Evento criado com sucesso!'
        else
            render(turbo_stream: turbo_stream.replace('events_form', partial: 'events/form', locals: { event: @event }))
        end
    end

    def edit; end

    def update
        if @event.update(event_params)
            redirect_to root_path, notice: 'Evento editado com sucesso!'
        else
            render(turbo_stream: turbo_stream.replace('events_form', partial: 'events/form', locals: { event: @event }))
        end
    end

    private

    def set_event
        @event = Event.find(params[:id])
    end

    def event_params
        params.require(:event).permit(:title, :description, :start_time, :end_time)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.where(start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_form.html.erb
<div class="card-content">
  <%= form_with(model: @event, id: 'events_form', data: { turbo_frame: '_top'}) do |f| %>
    <div class="content">
      <% if @event.errors.any? %>
        <div class="notification is-danger">
          <%= @event.errors.first.full_message %>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title, class: 'label' %>
        <%= f.text_field :title, class: 'input' %>
      </div>

      <div class="field">
        <%= f.label :description, class: 'label' %>
        <%= f.text_area :description, class: 'textarea' %>
      </div>

      <div class="field">
        <%= f.label :start_time, class: 'label' %>
        <%= f.datetime_field :start_time, class: 'input', data: { controller: 'flatpickr' } %>
      </div>

      <div class="field">
        <%= f.label :end_time, class: 'label' %>
        <%= f.datetime_field :end_time, class: 'input datetime-input', data: { controller: 'flatpickr' } %>
      </div>
    </div>

    <div class="is-flex is-justify-content-flex-end">
      <%= link_to 'cancelar', root_path, class: 'button is-danger mx-1' %>
      <%= f.submit class: 'button is-primary mx-1' %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= turbo_frame_tag 'event-frame' do %>
  <div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">Editar Evento</p>
        </header>
        <section>
          <%= render 'form' %>
        </section>
      </div>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<%= turbo_frame_tag 'event-frame' do %>
  <div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">Novo Evento</p>
        </header>
        <section>
          <%= render 'form' %>
        </section>
      </div>
    </div>
  </div>
<% end %>

app/views/events/show.html.erb
<%= turbo_frame_tag 'event-frame' do %>
  <div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title"><%= @event.title %></p>
      </header>
      <section class="modal-card-body">
        <section>
          <p>
            <%= @event.description %>
          </p>
        </section>
        <hr>
        <section>
          <p>
            <strong>Data de Inicio:</strong>
            <span><%= @event.start_time.strftime('%d/%m/%Y - %H:%M') %></span>
          </p>
          <p>
            <strong>Date final:</strong>
            <span><%= @event.end_time.strftime('%d/%m/%Y - %H:%M') %></span>
          </p>
        </section>
      </section>
      <footer class="modal-card-foot">
        <%= link_to 'Fechar', root_path, class: 'button' %>
        <%= link_to 'Editar', edit_event_path(@event), data: { turbo_frame: 'edit-event' }, class: 'button' %>
      </footer>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container is-max-desktop">
    <section class="has-text-centered">
      <h1 class="title is-1">Rails Calendar</h1>
      <%= link_to 'Novo Evento', new_event_path, data: { turbo_frame: 'event-frame' }, class: 'button is-primary' %>

      <hr>
    </section>

    <%= month_calendar(events: @events) do |date, events| %>
        <div class="day">
            <%= date.day %>
        </div>
        <% events.each do |event| %>
          <span class="tag is-info is-rounded">
              <%= link_to event.title, event_path(event), data: { turbo_frame: 'event-frame' }, class: 'has-text-white' %>
          </span>
        <% end %>
    <% end %>

    <%= turbo_frame_tag 'event-frame' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCalendarApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" %>
    <%= stylesheet_link_tag "https://npmcdn.com/flatpickr/dist/themes/material_green.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div>
  <div class="level">
    <div class="level-item">
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: 'button is-link' %>
    </div>

    <div class="level-item">
      <span class="subtitle is-4"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    </div>

    <div class="level-item">
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: 'button is-link' %>
    </div>
  </div>

  <table class="table is-bordered is-fullwidth">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: Date.current == day ? 'is-selected' : calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>